name: "Release to SDKMan"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
jobs:
  sdkmanMinorRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "üì• Checkout repository"
        uses: actions/checkout@v4
        with:
          ref: v${{ github.event.inputs.version }}
      - name: "‚òïÔ∏è Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: "üêò Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      - name: "üöÄ Grails SDK Minor Release"
        run: ./gradlew sdkMinorRelease
        env:
          DEVELOCITY_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
          DEVELOCITY_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }}
          GVM_SDKVENDOR_KEY: ${{ secrets.GVM_SDKVENDOR_KEY }}
          GVM_SDKVENDOR_TOKEN: ${{ secrets.GVM_SDKVENDOR_TOKEN }}
      - name: "Set output"
        id: set_output
        run: |
          echo ::set-output name=release_version::$(cat $GITHUB_OUTPUT)
        env:
          GITHUB_OUTPUT: ${{ github.workspace }}/build/release_version
